spring:
  application:
    name: spring-ai-workshop
  ai:
    model:
      chat: ${PROVIDER:none}
    azure:
      openai:
        api-key: ${MODEL_API_KEY}
        endpoint: ${MODEL_ENDPOINT}
        chat:
          options:
            model: ${MODEL_NAME}
            deployment-name: ${DEPLOYMENT_NAME}
            temperature: ${TEMPERATURE:0.7}
    anthropic:
      api-key: ${MODEL_API_KEY}
      base-url: ${MODEL_ENDPOINT}
      chat:
        options:
          model: ${MODEL_NAME}
          temperature: ${TEMPERATURE:0.8}
      completions-path: ${COMPLETIONS:/v1/chat/completions}
    deepseek:
      api-key: ${MODEL_API_KEY}
      base-url: ${MODEL_ENDPOINT}
      chat:
        options:
          model: ${MODEL_NAME}
          temperature: ${TEMPERATURE:0.7F}
        completions-path: ${COMPLETIONS:/chat/completions}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      access: read_only
configuration:
  environment-variables:
    client-id: ${CLIENT_ID}
    installation: ${INSTALLATION}
    pem: ${PEM}