spring:
  application:
    name: spring-ai-workshop
  ai:
    azure:
      openai:
        api-key: ${MODEL_API_KEY}
        endpoint: ${MODEL_ENDPOINT}
        chat:
          options:
            model: ${MODEL_NAME}
            deployment-name: ${DEPLOYMENT_NAME}
            temperature: ${TEMPERATURE:1}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      access: read_only
configuration:
  environment-variables:
    client-id: ${CLIENT_ID}
    installation: ${INSTALLATION}
    pem: ${PEM}