name: AI Pull Request review

on:
  workflow_call:
    inputs:
      project-name:
        description: "Name of the project that the AI will review, ex: organization/project"
        required: true
        type: string
      pull-request-id:
        description: "Number of the pr that the AI will review, ex: 15"
        required: true
        type: number
    secrets:
      PROVIDER:
        required: true
      MODEL_API_KEY:
        required: true
      MODEL_NAME:
        required: true
      MODEL_ENDPOINT:
        required: true
      DEPLOYMENT_NAME:
        required: false
      PEM:
        required: true
      CLIENT_ID:
        required: true
      INSTALLATION:
        required: true
      TEMPERATURE:
        required: false
      COMPLETIONS:
        required: false

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'

      - name: Build Application
        run: mvn clean package -DskipTest

      - name: Build Docker Image
        run: docker build -t spring-ai-pr-reviewer .

      - name: Run Reviewer container with env variables
        run: |
          docker_run_args="-d --name spring-ai-pr-reviewer -p 8080:8080"

          docker_run_args="$docker_run_args -e PROVIDER=${{ secrets.PROVIDER }}"
          docker_run_args="$docker_run_args -e MODEL_API_KEY=${{ secrets.MODEL_API_KEY }}"
          docker_run_args="$docker_run_args -e MODEL_NAME=${{ secrets.MODEL_NAME }}"
          docker_run_args="$docker_run_args -e MODEL_ENDPOINT=${{ secrets.MODEL_ENDPOINT }}"
          docker_run_args="$docker_run_args -e PEM=${{ secrets.PEM }}"
          docker_run_args="$docker_run_args -e CLIENT_ID=${{ secrets.CLIENT_ID }}"
          docker_run_args="$docker_run_args -e INSTALLATION=${{ secrets.INSTALLATION }}"

          [ -n "${{ secrets.DEPLOYMENT_NAME }}" ] && docker_run_args="$docker_run_args -e DEPLOYMENT_NAME=${{ secrets.DEPLOYMENT_NAME }}"
          [ -n "${{ secrets.TEMPERATURE }}" ] && docker_run_args="$docker_run_args -e TEMPERATURE=${{ secrets.TEMPERATURE }}"
          [ -n "${{ secrets.COMPLETIONS }}" ] && docker_run_args="$docker_run_args -e COMPLETIONS=${{ secrets.COMPLETIONS }}"

          docker run $docker_run_args spring-ai-pr-reviewer

      - name: Tail logs and wait for health
        run: |
          while ! curl -f http://localhost:8080/actuator/health; do
            echo "Waiting for the app to be ready..."
            docker logs --tail 150 spring-ai-pr-reviewer
            sleep 10
          done

      - name: Run Review
        run: |
          curl -X POST "http://localhost:8080/review?project=${{ inputs.project-name }}&pullrequest=${{ inputs.pull-request-id }}"

      - name: Stop and remove Reviewer container
        if: always()
        run: docker stop spring-ai-pr-reviewer && docker rm spring-ai-pr-reviewer